package dev.tommasop1804.kutils.classes.money

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.SerializerProvider
import dev.tommasop1804.kutils.*
import dev.tommasop1804.kutils.classes.geography.*
import dev.tommasop1804.kutils.exceptions.*
import jakarta.persistence.AttributeConverter
import tools.jackson.databind.DeserializationContext
import tools.jackson.databind.SerializationContext
import tools.jackson.databind.ValueDeserializer
import tools.jackson.databind.ValueSerializer
import tools.jackson.databind.annotation.JsonDeserialize
import tools.jackson.databind.annotation.JsonSerialize

/**
 * A value class representing a BIC (Bank Identifier Code), also known as SWIFT code.
 * This class encapsulates the BIC value, ensures it adheres to the expected format,
 * and provides properties and functionality for extracting specific components
 * (e.g., bank code, country, location code, branch code) of the BIC.
 *
 * The BIC is comprised of the following parts:
 * - Bank Code: First four characters.
 * - Country Code: Two characters at positions 4 and 5.
 * - Location Code: Two characters at positions 6 and 7.
 * - Branch Code (Optional): Three characters at positions 8 to 10.
 *
 * This class enforces the validation of the BIC format upon initialization and
 * provides additional utilities such as serialization, deserialization, and database conversion.
 *
 * @property value The string representation of the BIC. This value is validated for format compliance upon instantiation.
 * @constructor Initializes the object with a BIC string after enforcing validation rules.
 * @since 3.0.0
 * @author Tommaso Pastorelli
 */
@JvmInline
@JsonSerialize(using = Bic.Companion.Serializer::class)
@JsonDeserialize(using = Bic.Companion.Deserializer::class)
@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = Bic.Companion.OldSerializer::class)
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = Bic.Companion.OldDeserializer::class)
@Suppress("unused")
value class Bic private constructor(val value: String) : CharSequence {
    /**
     * Represents the length of the BIC (Bank Identifier Code) string.
     * This property corresponds to the total number of characters in the underlying BIC value.
     *
     * @return the length of the BIC value.
     * @since 3.0.0
     */
    override val length
        get() = value.length

    /**
     * Retrieves the bank code extracted from the BIC value.
     * The bank code is determined by invoking a custom integer extension
     * function on the underlying BIC string to obtain the first four characters.
     *
     * @return a string representation of the bank code
     * @since 3.0.0
     */
    val bankCode: String
        get() = 4(value)

    /**
     * Represents a nullable [Country] determined by extracting a specific range
     * of characters from the `ofAlpha2` value (indices 4 to 5).
     *
     * This property provides a way to retrieve the country information based on
     * its two-character ISO 3166-1 alpha-2 country code.
     *
     * @return A [Country] instance if the extraction is successful; otherwise, null.
     * @since 3.0.0
     */
    val country: Country?
        get() = Country ofAlpha2 value[4..5]

    /**
     * Represents the location code extracted from a BIC (Bank Identifier Code).
     * The location code provides information about the geographical or operational
     * location of the bank.
     *
     * This value is generated by extracting characters at index positions 6 and 7
     * from the BIC string.
     *
     * Validity of the location code adheres to the format rules specified in the BIC standard.
     *
     * @since 3.0.0
     */
    val locationCode: String
        get() = value[6..7]

    /**
     * Retrieves the branch code portion of a BIC (Business Identifier Code).
     *
     * The branch code is a three-character code extracted from the 9th to 11th characters of the BIC value.
     * It provides information about the specific branch of the financial institution.
     *
     * @return A string containing the branch code, or a default placeholder (e.g., "XXX") if unspecified.
     * @throws IndexOutOfBoundsException If the BIC value does not have sufficient length to include a branch code.
     * @since 3.0.0
     */
    val branchCode: String
        get() = try { value[8..10] } catch (_: StringIndexOutOfBoundsException) { DEFAULT_BRANCH_CODE }

    /**
     * Secondary constructor for the `BIC` value class.
     *
     * Initializes the `BIC` instance by accepting a `CharSequence` and performing
     * transformations to sanitize and format the input appropriately. Converts
     * the input into uppercase and removes any spaces within the input.
     *
     * @param value The `CharSequence` to initialize the `BIC` value from.
     *
     * @throws MalformedInputException if the resulting string does not conform
     * to the expected BIC format.
     *
     * @since 3.0.0
     */
    constructor(value: CharSequence) : this(+(value.toString() - Char.SPACE))

    init {
        Regex("[A-Z]{6}[0-9A-Z]{2}([0-9A-Z]{3})?")(value) || throw MalformedInputException("Invalid BIC format")
    }
    
    companion object {
        /**
         * Represents the default branch code used in BIC (Bank Identifier Code) when no specific branch
         * is designated. This is typically set to "XXX" and serves as a placeholder indicating a default
         * or primary branch of a given BIC.
         *
         * This constant is primarily used in scenarios where the branch portion of the BIC is either
         * optional or not explicitly defined.
         *
         * @since 3.0.0
         */
        private const val DEFAULT_BRANCH_CODE = "XXX"

        /**
         * Validates whether the given character sequence is a valid BIC (Bank Identifier Code) format.
         * A BIC is typically an 8 or 11-character alphanumeric code used to identify banks and financial institutions.
         *
         * The validation will verify whether the input adheres to the expected structure and rules for BICs.
         *
         * @receiver The character sequence to be validated as a BIC.
         * @return `true` if the input is a valid BIC, `false` otherwise.
         * @since 3.0.0
         */
        fun CharSequence.isValidBic() = runCatching { Bic(this) }.isSuccess

        /**
         * Attempts to convert the current `CharSequence` into a `BIC` instance.
         * If the conversion succeeds, the resulting `BIC` object is wrapped in a `Result`.
         * If the conversion fails (e.g., the input does not conform to the expected BIC format),
         * the resulting `Result` will contain the exception that was thrown.
         *
         * @receiver The `CharSequence` to be converted into a `BIC`.
         * @return A `Result` containing the successfully created `BIC` instance or a failure wrapping the exception.
         * @since 3.0.0
         */
        fun CharSequence.toBic() = runCatching { Bic(this) }

        class Serializer : ValueSerializer<Bic>() {
            override fun serialize(value: Bic, gen: tools.jackson.core.JsonGenerator, ctxt: SerializationContext) {
                gen.writeString(value.value)
            }
        }

        class Deserializer : ValueDeserializer<Bic>() {
            override fun deserialize(p: tools.jackson.core.JsonParser, ctxt: DeserializationContext) = Bic(p.string)
        }

        class OldSerializer : JsonSerializer<Bic>() {
            override fun serialize(value: Bic, gen: JsonGenerator, serializers: SerializerProvider) =
                gen.writeString(value.value)
        }

        class OldDeserializer : JsonDeserializer<Bic>() {
            override fun deserialize(p: JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): Bic = Bic(p.text)
        }

        @jakarta.persistence.Converter(autoApply = true)
        class Converter : AttributeConverter<Bic?, String?> {
            override fun convertToDatabaseColumn(attribute: Bic?): String? = attribute?.value
            override fun convertToEntityAttribute(dbData: String?): Bic? = dbData?.let { Bic(it) }
        }
    }

    /**
     * Retrieves the primary component of the BIC (Bank Identifier Code).
     *
     * This component typically represents the primary identifier part of the BIC value.
     * It is extracted from the underlying data structure and returned as a single value.
     *
     * @return The primary component of the BIC.
     * @since 3.1.0
     */
    operator fun component1() = value
    /**
     * Provides the second component of the BIC (Business Identifier Code), specifically the bank code.
     * 
     * This method allows destructuring declarations, enabling the bank code to be retrieved directly 
     * when unpacking a `Bic` instance.
     *
     * @return The bank code as part of the BIC.
     * @since 3.1.0
     */
    operator fun component2() = bankCode
    /**
     * Provides destructuring support for extracting the country code from a BIC (Bank Identifier Code).
     *
     * This operator function corresponds to the third component in a destructuring declaration.
     *
     * @return The country code of the BIC as a string.
     * @since 3.1.0
     */
    operator fun component3() = country
    /**
     * Provides the destructuring component that represents the `locationCode` field of the BIC.
     *
     * This operator function is used to retrieve the fourth component of the BIC representation
     * during destructuring declarations or other contexts that utilize component functions.
     *
     * @return The `locationCode` associated with this BIC.
     * @since 3.1.0
     */
    operator fun component4() = locationCode
    /**
     * Retrieves the branch code component of this BIC (Bank Identifier Code).
     *
     * This method is a part of the `componentN` family of functions providing
     * destructuring capabilities. Specifically, `component5` corresponds to 
     * the branch code segment of the BIC.
     *
     * @return The branch code component of this BIC.
     * @since 3.1.0
     */
    operator fun component5() = branchCode
    
    /**
     * Returns the character at the specified [index] in the underlying string representation of the BIC.
     *
     * @param index the index of the character to be returned. Must be within the bounds of the string length.
     * @return the character at the specified position.
     * @throws IndexOutOfBoundsException if the index is out of bounds.
     * @since 3.0.0
     */
    override fun get(index: Int) = value[index]

    /**
     * Returns a new character sequence that is a subsequence of this sequence. The subsequence starts at the specified
     * [startIndex] and ends right before the specified [endIndex].
     *
     * @param startIndex the starting index of the subsequence, inclusive. Must be non-negative and less than or equal to [endIndex].
     * @param endIndex the ending index of the subsequence, exclusive. Must be non-negative and greater than or equal to [startIndex].
     * @since 3.0.0
     */
    override fun subSequence(startIndex: Int, endIndex: Int) = value.subSequence(startIndex, endIndex)

    /**
     * Returns the string representation of the BIC value.
     *
     * This method overrides the default implementation to provide
     * the raw string value of the BIC.
     *
     * @return The underlying string value of this BIC instance.
     * @since 3.0.0
     */
    override fun toString() = value

    /**
     * Returns a string representation of the BIC value, optionally omitting the default branch code "XXX".
     *
     * @param omitDefaultBranchCode When `true`, the default branch code "XXX" will be omitted
     *        from the end of the string if it exists. When `false`, the full BIC value, including
     *        the branch code, will be returned.
     * @return The string representation of the BIC value, with or without the default branch code.
     * @since 3.0.0
     */
    fun toString(omitDefaultBranchCode: Boolean) = if (omitDefaultBranchCode) {
        if (DEFAULT_BRANCH_CODE in value) value - 3
        else value
    } else {
        if (value.length == 8) value + DEFAULT_BRANCH_CODE
        else value
    }
}