/*
 * Copyright © 2026 Tommaso Pastorelli (TommasoP1804) | Kotlin-Utils
 */

@file:JvmName("SequenceUtilsKt")
@file:Suppress("unused", "kutils_collection_declaration", "kutils_take_as_int_invoke", "kutils_drop_as_int_invoke", "deprecation",
    "RETURN_VALUE_NOT_USED_COERCION"
)
@file:Since("1.0.0")
@file:OptIn(ExperimentalContracts::class, ExperimentalExtendedContracts::class)
@file:MustUseReturnValues

package dev.tommasop1804.kutils

import Break
import Continue
import dev.tommasop1804.kutils.annotations.*
import dev.tommasop1804.kutils.classes.constants.*
import dev.tommasop1804.kutils.exceptions.*
import kotlin.contracts.ExperimentalContracts
import kotlin.contracts.ExperimentalExtendedContracts
import kotlin.contracts.InvocationKind
import kotlin.contracts.contract
import kotlin.reflect.KFunction
import kotlin.reflect.KParameter
import kotlin.reflect.KProperty

/**
 * Determines whether the sequence contains exactly one element.
 *
 * @return `true` if the sequence has exactly one element, otherwise `false`.
 * @since 1.0.0
 */
val  <E> Sequence<E>.isSingleElement: Boolean get() = singleOrNull().isNotNull()
/**
 * Checks if the sequence does not contain exactly one element.
 *
 * This function determines whether the sequence either has no elements
 * or contains more than one element.
 *
 * @return `true` if the sequence does not contain exactly one element,
 * `false` if it contains exactly one element.
 * @since 1.0.0
 */
val <E> Sequence<E>.isNotSingleElement: Boolean get() = !isSingleElement

/**
 * Transforms a [Sequence] into a [Map] by applying the provided key and value mapping functions.
 *
 * @param key a function that defines how to transform each element of the sequence into a key.
 * @param value a function that defines how to transform each element of the sequence into a value.
 * @return a [Map] containing key-value pairs generated by applying the key and value functions
 *         to elements of the original sequence.
 * @since 1.0.0
 */
fun <E, K, V> Sequence<E>.associate(key: Transformer<E, K>, value: Transformer<E, V>) =
    associate { key(it) to value(it) }

/**
 * Populates the given [destination] mutable map with key-value pairs where keys and values are provided
 * by the [key] and [value] functions applied to elements of the sequence.
 *
 * The sequence is iterated to generate pairs, which are then added to the [destination] map.
 *
 * @param destination The mutable map to which the generated key-value pairs will be added.
 * @param key A function that computes a key from an element of the sequence.
 * @param value A function that computes a value from an element of the sequence.
 * @param E The type of the elements in the sequence.
 * @param K The type of the keys in the map.
 * @param V The type of the values in the map.
 * @param M The type of the destination mutable map (or a supertype of it).
 * @since 1.0.0
 */
fun <E, K, V, M : MutableMap<in K, in V>> Sequence<E>.associateTo(
    destination: M,
    key: Transformer<E, K>,
    value: Transformer<E, V>
) = associateTo(destination) { key(it) to value(it) }

/**
 * Invokes the integer to either take a specified number of elements from the sequence
 * if the integer is positive, or drop a specified number of elements when the integer is negative.
 *
 * @param sequence the sequence of elements to be acted upon.
 * @return a new sequence with elements taken or dropped based on the integer value.
 * @since 1.0.0
 */
@Deprecated("Use take or drop instead", ReplaceWith("if (this > 0) sequence.take(this) else sequence.drop(-this)"))
operator fun <T> Int.invoke(sequence: Sequence<T>): Sequence<T> {
    return if (this > 0) sequence.take(this)
    else sequence.drop(-this)
}
/**
 * Applies the given predicate function to filter the elements of the sequence.
 *
 * This operator function allows applying a custom filtering logic encapsulated in the `Predicate`.
 *
 * @param filter A predicate function that determines whether an element should be included in the resulting sequence.
 * @return A sequence containing only the elements that match the provided predicate.
 * @since 1.1.1
 */
inline operator fun <E> Sequence<E>.invoke(crossinline filter: Predicate<E>): Sequence<E> = filter { filter(it) }

/**
 * Extension operator function for `Sequence` that retrieves the first element satisfying the provided predicate.
 *
 * @param find A lambda function or predicate that is applied to each element of the sequence to determine the desired element.
 * @return The first element that matches the predicate, or `null` if no such element is found.
 * @since 1.1.1
 */
inline operator fun <E> Sequence<E>.get(find: Predicate<E>): E? = find { find(it) }
/**
 * Finds the first element in a sequence that satisfies the given predicate, or throws a provided exception if no such element is found.
 *
 * @param find a predicate that evaluates each element of the sequence to determine if it matches the condition.
 * @param lazyException a supplier for the exception to be thrown if no element satisfies the given predicate.
 * @return the first element in the sequence that satisfies the predicate.
 * @since 1.1.1
 */
inline operator fun <E> Sequence<E>.get(find: Predicate<E>, lazyException: ThrowableSupplier): E = find { find(it) } ?: throw lazyException()

/**
 * Returns the first element in the sequence that matches the given [predicate] or throws an exception
 * provided by the [lazyException] supplier if no such element is found.
 *
 * @param lazyException a supplier that provides the exception to be thrown if no matching element is found
 * @param predicate a condition to evaluate on elements of the sequence
 * @return the first element in the sequence that satisfies the [predicate]
 * @throws Throwable the exception provided by the [lazyException] supplier if no element matches the [predicate]
 * @since 1.1.1
 */
inline fun <E> Sequence<E>.findOrThrow(lazyException: ThrowableSupplier, predicate: Predicate<E>): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return find(predicate) ?: throw lazyException()
}

/**
 * Merges the current sequence with additional sequences and returns the resulting sequence.
 * 
 * If the current sequence is null or empty and no additional sequences are provided, 
 * it returns an empty sequence. If additional sequences are provided, merges them iteratively.
 *
 * @param sequences Additional sequences to be merged with the current sequence.
 * @return A merged sequence containing elements from the current sequence and the additional sequences.
 * @since 1.0.0
 */
@Suppress("UNCHECKED_CAST")
fun <T: Sequence<E>, E> T?.merge(vararg sequences: Sequence<E>): T {
    return when {
        sequences.isEmpty() && (isNull() || none()) -> emptySequence<E>() as T
        sequences.isEmpty() -> this as T
        isNull() || none() -> sequences.first().merge(*sequences.drop(1).toTypedArray()) as T
        else -> sequences.fold(this) { acc, sequence -> acc.plus(sequence) as T }
    }
}

/**
 * Checks if the sequence contains any of the specified elements.
 *
 * This function evaluates lazily and stops as soon as any element in the sequence
 * matches one of the provided elements. The function uses the `in` operator internally
 * to check membership.
 *
 * @param elements the elements to be checked against the sequence.
 * @since 1.0.0
 */
fun <E> Sequence<E>.containsAny(vararg elements: E) = any { it in elements }

/**
 * Checks if none of the elements in the sequence are present in the specified elements.
 *
 * @param elements The elements to check against the sequence.
 * @return `true` if none of the elements in the sequence are present in the specified elements, `false` otherwise.
 * @since 1.0.0
 */
fun <E> Sequence<E>.containsNone(vararg elements: E) = none { it in elements }

/**
 * Checks if any element in the sequence satisfies the given predicate.
 *
 * @param predicate A lambda function that takes an element of the sequence and returns true if the condition is met, false otherwise.
 * @since 1.1.0
 */
operator fun <E> Sequence<E>.contains(predicate: Predicate<E>) = any { predicate(it) }

/**
 * Returns the first element of the sequence or throws an exception provided by the given lazy exception supplier
 * if the sequence is empty.
 *
 * @param lazyException A supplier function that provides the exception to throw when the sequence is empty.
 * @return The first element of the sequence.
 * @since 1.0.0
 */
@IgnorableReturnValue
infix fun <E> Sequence<E>.firstOrThrow(lazyException: ThrowableSupplier): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return firstOrNull() ?: throw lazyException()
}
/**
 * Returns the first element of the sequence that matches the given [predicate].
 * If no elements match the [predicate], the exception provided by [lazyException] is thrown.
 *
 * @param lazyException A supplier that provides the exception to be thrown if no element matches the [predicate].
 * @param predicate A condition to be applied to each element to determine if it matches.
 * @return The first element that matches the [predicate].
 * @throws Throwable If no element matching the [predicate] is found.
 * @since 1.0.0
 */
@IgnorableReturnValue
fun <E> Sequence<E>.firstOrThrow(lazyException: ThrowableSupplier, predicate: Predicate<E>): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return firstOrNull(predicate) ?: throw lazyException()
}

/**
 * Returns the first element of the sequence or the result of [default] if the sequence is empty.
 *
 * @param default a supplier function that provides a value to return if the sequence is empty.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.firstOr(default: Supplier<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    return firstOrNull() ?: default()
}
/**
 * Returns the first element in the sequence that matches the given [predicate].
 * If no such element is found, returns the result of calling the [default] supplier.
 *
 * @param E the type of elements in the sequence
 * @param default a supplier function that provides a default value if no element matches the [predicate]
 * @param predicate a function that defines the condition to match the elements in the sequence
 * @return the first element matching the [predicate], or the result of the [default] supplier if no match is found
 *
 * @since 1.0.0
 */
fun <E> Sequence<E>.firstOr(default: Supplier<E>, predicate: Predicate<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    return firstOrNull(predicate) ?: default()
}

/**
 * Iterates over each element in the sequence and applies the given [block] to it.
 *
 * The sequence itself is returned after the operation, allowing for chaining.
 *
 * @param E the type of elements in the sequence.
 * @param block a lambda function that takes an element of the sequence as a parameter
 * and performs an operation on it.
 * @since 2.0.0
 */
inline fun <E> Sequence<E>.peek(block: Consumer<E>) = apply {
    for (element in this@peek) block(element)
}

/**
 * Returns a sequence containing all elements of the original sequence except those that match the given predicate.
 *
 * @param filterNot The predicate used to test elements for exclusion from the resulting sequence.
 * @return A sequence with elements that do not match the specified predicate.
 * @since 3.5.2
 */
operator fun <E> Sequence<E>.minus(filterNot: Predicate<E>) = filterNot(filterNot)

/**
 * Stands for `controlledEach`. You can use [continueLoop] and [breakLoop].
 *
 * Iterates over each element in the sequence, executing the provided block with a `LoopContext` and the current element.
 * The block operation can control the flow using `Break` and `Continue` exceptions.
 *
 * @param block A callback function that takes a `LoopContext` and the current element of the sequence.
 * @since 2.0.0
 */
@IgnorableReturnValue
inline fun <E> Sequence<E>.cForEach(block: ReceiverBiConsumer<LoopContext, E>) = apply {
    with(LoopContext()) {
        for (element in this@cForEach) {
            try {
                block(element)
            } catch (b: Break) {
                break
            } catch (c: Continue) {
                continue
            }
        }
    }
}

/**
 * Stands for `controlledEach`. You can use [continueLoop] and [breakLoop].
 *
 * Iterates over the elements of the sequence along with their indices and allows the execution of a block
 * of code for each element. The current iteration context and index are also passed to the block.
 *
 * @param E The type of elements contained in the sequence.
 * @param block A lambda function that takes three parameters: the current loop context, the index of the current
 * element, and the current element itself. Executed for each element in the sequence.
 * @since 2.0.0
 */
@IgnorableReturnValue
inline fun <E> Sequence<E>.cForEachIndexed(block: ReceiverTriConsumer<LoopContext, Int, E>) = apply {
    with(LoopContext()) {
        for ([index, element] in withIndex()) {
            try {
                block(index, element)
            } catch (b: Break) {
                break
            } catch (c: Continue) {
                continue
            }
        }
    }
}

/**
 * Stands for `eachWithReturn`. You can use [continueLoop] and [breakLoop] to return a value.
 *
 * Executes the specified action for each element in the sequence and provides a mechanism to exit the loop
 * with a value using `Break` or skip the current iteration using `Continue`.
 *
 * @param action A lambda function accepting a `LoopContext` and an element of the sequence, where the action to be performed is defined.
 * @return The result carried by a `Break` instance if it is thrown during iteration, or `null` if the loop completes normally.
 * @since 2.0.0
 */
@Suppress("UNCHECKED_CAST")
inline fun <E, R> Sequence<E>.rForEach(action: ReceiverBiConsumer<LoopContext, E>): R? {
    with(LoopContext()) {
        for (element in this@rForEach) {
            try {
                action(element)
            } catch (b: Break) {
                return b.result as? R
            } catch (c: Continue) {
                continue
            }
        }
    }
    return null
}
/**
 * Stands for `eachWithReturn`. You can use [continueLoop] and [breakLoop] to return a value.
 *
 * Iterates over the elements of the sequence along with their indices,
 * providing a context object and supporting control flow through custom exceptions.
 * Allows the loop to be interrupted with a result using the `Break` exception or skipped using the `Continue` exception.
 *
 * @param action A lambda or function accepting the loop context, the index of the current element,
 * and the element itself. The lambda may throw a `Break` exception to stop the loop and return a result,
 * or a `Continue` exception to skip to the next iteration.
 * @return The result specified in the `Break` exception if thrown, or `null` if the loop completes normally.
 * @since 2.0.0
 */
@Suppress("UNCHECKED_CAST")
inline fun <E, R> Sequence<E>.rForEachIndexed(action: ReceiverTriConsumer<LoopContext, Int, E>): R? {
    with(LoopContext()) {
        for ([index, element] in withIndex()) {
            try {
                action(index, element)
            } catch (b: Break) {
                return b.result as? R
            } catch (c: Continue) {
                continue
            }
        }
    }
    return null
}

/**
 * Splits a sequence into chunks where each chunk ends when the given predicate evaluates to true for an element.
 *
 * @param predicate A function that takes an element of the sequence and returns true when a chunk should end.
 * @return A sequence of lists, where each list represents a chunk of the original elements partitioned by the predicate.
 * @since 1.0.0
 */
fun <E> Sequence<E>.chunkedWhile(predicate: Predicate<E>): Sequence<List<E>> = run {
    val result = mutableListOf<List<E>>()
    var current = mutableListOf<E>()
    for (e in this) {
        current += e
        if (predicate(e)) {
            result.add(current)
            current = mutableListOf()
        }
    }
    if (current.isNotEmpty()) result.add(current)
    return result.asSequence()
}

/**
 * Repeats each element of the sequence a specified number of times and returns the resulting sequence.
 *
 * @param n The number of times each element of the sequence should be repeated. Must be a non-negative integer.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.repeatEach(n: Int) = flatMap { e -> e.asSingleList() * n }

/**
 * Returns the single element of the sequence if it contains exactly one element.
 *
 * Throws a [NoSuchElementException] if the sequence is empty.
 * Throws a [TooManyElementsException] if the sequence contains more than one element.
 *
 * @throws NoSuchElementException if the sequence is empty.
 * @throws TooManyElementsException if the sequence contains more than one element.
 * @receiver Sequence<E> The sequence to retrieve the single element from.
 * @return The only element in the sequence.
 * @since 1.0.0
 */
fun <E> Sequence<E>.onlyElement() = run {
    if (none()) throw NoSuchElementException()
    else if (singleOrNull().isNotNull()) single() else throw TooManyElementsException()
}
/**
 * Returns the single element of the sequence if it contains exactly one element, or `null` if the sequence is empty
 * or contains more than one element.
 *
 * This function terminates as soon as it can determine the result: it will stop processing further elements once
 * the second element is encountered if the sequence has more than one.
 *
 * It is equivalent to calling [singleOrNull] but provides clear intent when used in cases where you expect the
 * sequence to have zero or one element.
 *
 * @receiver The sequence to evaluate.
 * @return The single element if the sequence contains exactly one element, or `null` otherwise.
 * @since 1.0.0
 */
fun <E> Sequence<E>.onlyElementOrNull() = singleOrNull()
/**
 * Returns the single element of this sequence if it contains exactly one element, or the result of the provided
 * default supplier if the sequence is empty or contains more than one element.
 *
 * @param default A supplier function that provides a default value if the sequence is either empty or has more
 * than one element.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.onlyElementOr(default: Supplier<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    return singleOrNull() ?: default()
}
/**
 * Returns the only element of the sequence or throws an exception provided by the given supplier
 * if the sequence contains zero or more than one element.
 *
 * @param lazyException A supplier function that provides the exception to be thrown if the sequence
 * does not contain exactly one element.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.onlyElementOrThrow(lazyException: ThrowableSupplier): E & Any {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return singleOrNull() ?: throw lazyException()
}
/**
 * Returns the only element in the sequence that matches the given predicate.
 * Throws an exception if there are no elements in the sequence, if no elements
 * match the predicate, or if more than one element matches the predicate.
 *
 * @param predicate A lambda function that defines the condition to match the desired element in the sequence.
 * @throws NoSuchElementException if the sequence is empty.
 * @throws TooManyElementsException if more than one element matches the predicate.
 * @throws NoSuchElementException if no elements match the predicate.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.onlyElement(predicate: Predicate<E>) = run {
    if (none()) throw NoSuchElementException()
    else if (singleOrNull(predicate).isNotNull()) single() else throw TooManyElementsException()
}
/**
 * Returns the single element of the sequence that matches the given [predicate], or `null` if no such element was found.
 * If more than one element matches the [predicate], an exception will be thrown.
 *
 * @param predicate A function that defines the condition to match the element.
 * @return The single element matching the [predicate], or `null` if no matching element is found.
 * @throws IllegalArgumentException if more than one element matches the [predicate].
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.onlyElementOrNull(predicate: Predicate<E>) = singleOrNull(predicate)
/**
 * Returns the single element of this sequence that matches the given [predicate], or the value
 * provided by [default] if no such element is found.
 *
 * The operation will throw an exception if there is more than one matching element.
 *
 * @param default a supplier providing the fallback value if no element matches the [predicate]
 * @param predicate a predicate to determine the element that should be returned
 * @since 1.0.0
 */
fun <E> Sequence<E>.onlyElementOr(default: Supplier<E>, predicate: Predicate<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    return singleOrNull(predicate) ?: default()
}
/**
 * Returns the single element of the sequence matching the given [predicate], or throws the exception provided
 * by the [lazyException] if no such element exists or if more than one element matches the [predicate].
 *
 * @param lazyException a supplier for the exception to be thrown when no element or multiple elements match the predicate
 * @param predicate a condition that the element needs to satisfy
 * @since 1.0.0
 */
@IgnorableReturnValue
fun <E> Sequence<E>.onlyElementOrThrow(lazyException: ThrowableSupplier, predicate: Predicate<E>): E & Any {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return singleOrNull(predicate) ?: throw lazyException()
}

/**
 * Returns the second element of the sequence.
 *
 * The sequence is iterated lazily through its iterator, consuming at most two elements.
 *
 * @receiver The sequence from which the second element is to be accessed.
 * @return The second element of the sequence.
 * @throws NoSuchElementException If the sequence contains fewer than two elements.
 * @since 4.1.0
 */
fun <E> Sequence<E>.second(): E {
    val iterator = iterator()
    kotlin.repeat(1) {
        if (!iterator.hasNext()) throw NoSuchElementException("Sequence doesn't allow to get second element.")
        iterator.next()
    }
    if (!iterator.hasNext()) throw NoSuchElementException("Sequence doesn't allow to get second element.")
    return iterator.next()
}
/**
 * Returns the second element of the sequence that matches the given predicate.
 *
 * Filters the sequence based on the provided predicate and retrieves the second element
 * from the filtered sequence. If there are fewer than two elements matching the predicate,
 * a [NoSuchElementException] is thrown.
 *
 * @param predicate a condition to filter the elements in the sequence.
 * @return the second element that matches the predicate.
 * @throws NoSuchElementException if there are fewer than two elements matching the predicate.
 * @since 4.1.0
 */
fun <E> Sequence<E>.second(predicate: Predicate<E>) = filter(predicate).second()
/**
 * Returns the second element of the sequence or `null` if the sequence contains
 * fewer than two elements.
 *
 * The sequence is iterated lazily through its iterator, consuming at most two elements.
 *
 * @receiver The sequence from which the second element is to be accessed.
 * @return The second element of the sequence, or `null` if it contains fewer than two elements.
 * @since 4.1.0
 */
fun <E> Sequence<E>.secondOrNull(): E? {
    val iterator = iterator()
    kotlin.repeat(1) {
        if (!iterator.hasNext()) return null
        iterator.next()
    }
    return if (iterator.hasNext()) iterator.next() else null
}
/**
 * Returns the second element in the sequence that matches the specified [predicate],
 * or `null` if no such element is found or if there are fewer than two matching elements.
 *
 * @param predicate a function that defines the condition to filter the elements of the sequence.
 * @return the second element satisfying the given predicate, or `null` if no such element exists.
 * @since 4.1.0
 */
fun <E> Sequence<E>.secondOrNull(predicate: Predicate<E>) = filter(predicate).secondOrNull()
/**
 * Returns the second element of the sequence if it exists, or throws the exception provided by the
 * given `lazyException` supplier if the sequence contains fewer than two elements.
 *
 * @param lazyException A supplier function that produces the exception to be thrown if the sequence has fewer than two elements.
 * @since 4.1.0
 */
@IgnorableReturnValue
fun <E> Sequence<E>.secondOrThrow(lazyException: ThrowableSupplier): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    val iterator = iterator()
    kotlin.repeat(1) {
        if (!iterator.hasNext()) throw lazyException()
        iterator.next()
    }
    if (!iterator.hasNext()) throw lazyException()
    return iterator.next()
}
/**
 * Returns the second element in the sequence that matches the given predicate or throws an exception
 * provided by the given `lazyException` supplier if no such element exists.
 *
 * @param lazyException a supplier for the exception to throw if there are not enough matching elements
 * @param predicate a condition to filter elements of the sequence
 * @since 4.1.0
 */
@IgnorableReturnValue
fun <E> Sequence<E>.secondOrThrow(lazyException: ThrowableSupplier, predicate: Predicate<E>): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return filter(predicate).secondOrThrow(lazyException)
}
/**
 * Returns the second element of the sequence if it exists; otherwise, returns the value supplied by the given default supplier.
 *
 * @param default A supplier function that provides a default value when the sequence does not contain at least two elements.
 * @return The second element of the sequence, or the result of invoking the default supplier if the sequence has less than two elements.
 * @since 4.1.0
 */
fun <E> Sequence<E>.secondOr(default: Supplier<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    val iterator = iterator()
    kotlin.repeat(1) {
        if (!iterator.hasNext()) return default()
        iterator.next()
    }
    return if (iterator.hasNext()) iterator.next() else default()
}
/**
 * Returns the second element in the sequence that matches the given predicate, or the value provided by
 * the default supplier if no such element exists or there are less than two elements.
 *
 * @param default A supplier function that provides a default value if the sequence does not contain
 *                a valid second element matching the predicate.
 * @param predicate A function that determines whether a given element in the sequence matches the criteria.
 * @since 4.1.0
 */
fun <E> Sequence<E>.secondOr(default: Supplier<E>, predicate: Predicate<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    return filter(predicate).secondOr(default)
}

/**
 * Returns the third element of the sequence.
 *
 * The sequence is iterated lazily through its iterator, consuming at most three elements.
 *
 * @throws NoSuchElementException if the sequence contains fewer than three elements.
 * @return the third element of the sequence.
 * @since 4.1.0
 */
fun <E> Sequence<E>.third(): E {
    val iterator = iterator()
    kotlin.repeat(2) {
        if (!iterator.hasNext()) throw NoSuchElementException("Sequence doesn't allow to get third element.")
        iterator.next()
    }
    if (!iterator.hasNext()) throw NoSuchElementException("Sequence doesn't allow to get third element.")
    return iterator.next()
}
/**
 * Returns the third element in the sequence matching the given predicate after filtering.
 *
 * The method first filters the elements of the sequence using the provided predicate and
 * then attempts to retrieve the third element from the filtered sequence. If the filtered
 * sequence has less than three elements, a [NoSuchElementException] is thrown.
 *
 * @param predicate A predicate to filter the elements of the sequence.
 * @since 4.1.0
 */
fun <E> Sequence<E>.third(predicate: Predicate<E>) = filter(predicate).third()
/**
 * Returns the third element of the sequence if it contains at least three elements, or `null` otherwise.
 *
 * The sequence is iterated lazily through its iterator, consuming at most three elements.
 *
 * @receiver The sequence from which the third element is accessed.
 * @return The third element of the sequence, or `null` if it has fewer than three elements.
 * @since 4.1.0
 */
fun <E> Sequence<E>.thirdOrNull(): E? {
    val iterator = iterator()
    kotlin.repeat(2) {
        if (!iterator.hasNext()) return null
        iterator.next()
    }
    return if (iterator.hasNext()) iterator.next() else null
}
/**
 * Returns the third element that matches the given [predicate], or `null` if no such element exists.
 *
 * The search for the matching element is performed by filtering the sequence based on the given [predicate].
 *
 * @param predicate the condition used to filter the elements of the sequence.
 * @return the third element matching the [predicate], or `null` if there are less than three matching elements.
 * @since 4.1.0
 */
fun <E> Sequence<E>.thirdOrNull(predicate: Predicate<E>) = filter(predicate).thirdOrNull()
/**
 * Returns the third element of the sequence if it exists, otherwise throws an exception provided by the given supplier.
 *
 * @param lazyException A supplier that provides the exception to be thrown if the sequence has fewer than three elements.
 * @throws Throwable The exception provided by the supplier if the sequence size is less than three.
 * @return The third element of the sequence.
 * @since 4.1.0
 */
@IgnorableReturnValue
fun <E> Sequence<E>.thirdOrThrow(lazyException: ThrowableSupplier): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    val iterator = iterator()
    kotlin.repeat(2) {
        if (!iterator.hasNext()) throw lazyException()
        iterator.next()
    }
    if (!iterator.hasNext()) throw lazyException()
    return iterator.next()
}
/**
 * Returns the third element in the sequence that matches the given predicate or throws an exception
 * provided by the lazyException supplier if there are less than three matching elements.
 *
 * @param lazyException a supplier that provides the exception to be thrown if the conditions are not met
 * @param predicate a condition to filter elements in the sequence
 * @since 4.1.0
 */
@IgnorableReturnValue
fun <E> Sequence<E>.thirdOrThrow(lazyException: ThrowableSupplier, predicate: Predicate<E>): E {
    contract {
        callsInPlace(lazyException, InvocationKind.AT_MOST_ONCE)
    }
    return filter(predicate).thirdOrThrow(lazyException)
}
/**
 * Returns the third element of the sequence if it exists; otherwise, evaluates and returns the
 * result of the provided default supplier.
 *
 * @param default A supplier function that provides a default value to return if the sequence
 * has fewer than three elements.
 * @return The third element of the sequence if present, or the default value provided by the supplier.
 * @since 4.1.0
 */
fun <E> Sequence<E>.thirdOr(default: Supplier<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    val iterator = iterator()
    kotlin.repeat(2) {
        if (!iterator.hasNext()) return default()
        iterator.next()
    }
    return if (iterator.hasNext()) iterator.next() else default()
}
/**
 * Returns the third element of the sequence that matches the given predicate if it exists; otherwise, returns the value supplied by the provided default supplier.
 * The matching elements are determined by filtering the sequence based on the given predicate.
 *
 * @param default A supplier function that provides a default value when the sequence does not contain at least three elements
 *                matching the given predicate.
 * @param predicate A predicate function used to filter the sequence.
 * @since 4.1.0
 */
fun <E> Sequence<E>.thirdOr(default: Supplier<E>, predicate: Predicate<E>): E {
    contract {
        callsInPlace(default, InvocationKind.AT_MOST_ONCE)
    }
    return filter(predicate).thirdOr(default)
}

/**
 * Checks if the sequence is empty.
 *
 * This function evaluates whether the sequence contains no elements.
 * It returns `true` if the sequence is empty, and `false` otherwise.
 *
 * Note that this function evaluates the sequence. Be cautious when using
 * it with potentially infinite sequences, as it might result in infinite execution.
 *
 * @receiver Sequence<E> the sequence to be checked.
 * @return `true` if the sequence contains no elements, `false` otherwise.
 * @since 1.0.0
 */
fun <E> Sequence<E>.isEmpty() = none()
/**
 * Checks if the sequence is not empty.
 *
 * This function evaluates the sequence to determine if it contains at least one element.
 * It is a terminal operation that consumes elements of the sequence if it is not empty.
 *
 * @receiver The sequence to check.
 * @return `true` if the sequence contains at least one element, `false` otherwise.
 * @since 1.0.0
 */
fun <E> Sequence<E>.isNotEmpty() = any()

/**
 * Checks if the given sequence is either `null` or empty.
 *
 * This function uses a contract to indicate that when it returns `false`, the sequence is guaranteed to be non-null.
 *
 * @return `true` if the sequence is `null` or contains no elements; otherwise `false`.
 * @since 1.0.0
 */
@OptIn(ExperimentalContracts::class)
@Suppress("kutils_null_check")
fun <E> Sequence<E>?.isNullOrEmpty(): Boolean {
    contract {
        returns(false) implies (this@isNullOrEmpty != null)
    }
    return isNull() || none()
}
/**
 * Checks if the given sequence is not null and not empty.
 *
 * @return `true` if the sequence is not null and contains at least one element, otherwise `false`.
 * @since 1.0.0
 */
@OptIn(ExperimentalContracts::class)
@Suppress("kutils_null_check")
fun <E> Sequence<E>?.isNotNullOrEmpty(): Boolean {
    contract {
        returns(true) implies (this@isNotNullOrEmpty != null)
    }
    return isNotNull() && any()
}

/**
 * Returns the original sequence if it is neither null nor empty; otherwise, it invokes the
 * specified [defaultValue] supplier and returns its result.
 *
 * This function uses a contract to ensure that the [defaultValue] supplier is invoked at most once.
 *
 * @param defaultValue a supplier function that provides a replacement sequence in case the
 *                     original sequence is null or empty
 * @return the original sequence if it's not null or empty; otherwise, the result of the [defaultValue] supplier
 * @since 1.0.0
 */
@OptIn(ExperimentalContracts::class)
inline infix fun <S : Sequence<E>, E> S?.ifNullOrEmpty(defaultValue: Supplier<S>): S {
    contract {
        callsInPlace(defaultValue, InvocationKind.AT_MOST_ONCE)
    }
    return if (isNullOrEmpty()) defaultValue() else this
}

/**
 * Invokes the given action if the sequence is not empty.
 *
 * This function checks whether the sequence contains at least one element.
 * If the sequence is not empty, the provided action is executed with the sequence as its receiver.
 * Otherwise, the sequence is returned unchanged.
 *
 * @param action A lambda function or receiver transformer to execute if the sequence is not empty.
 * @return The result of the action if the sequence is not empty, otherwise the original sequence.
 * @since 4.1.0
 */
@OptIn(ExperimentalContracts::class)
@Suppress("UNCHECKED_CAST")
@IgnorableReturnValue
inline fun <E, R> Sequence<E>.ifNotEmpty(action: ReceiverTransformer<Sequence<E>, R>): R {
    contract {
        callsInPlace(action, InvocationKind.AT_MOST_ONCE)
    }
    return (if (isNotEmpty()) action(this) else this) as R
}

/**
 * Executes the given action if the sequence is not null and not empty.
 *
 * @param action A functional operation to apply to the sequence if it is not null or empty.
 *               The sequence itself is provided as the receiver of the `action`.
 * @return The result of the `action` if the sequence is not null or empty, otherwise `null`.
 * @since 4.1.0
 */
@OptIn(ExperimentalExtendedContracts::class, ExperimentalContracts::class)
@Suppress("UNCHECKED_CAST")
@IgnorableReturnValue
inline fun <E, R> Sequence<E>?.ifNotNullOrEmpty(action: ReceiverTransformer<Sequence<E>, R>): R? {
    contract {
        callsInPlace(action, InvocationKind.AT_MOST_ONCE)
        (this@ifNotNullOrEmpty != null) implies returnsNotNull()
    }
    return (if (isNotNullOrEmpty()) action(this) else this) as R
}

/**
 * Checks if the sequence is null or empty. The operator function `not` is used as a negation
 * to verify whether the sequence contains any elements or exists at all.
 *
 * @return `true` if the sequence is either null or empty, `false` otherwise.
 * @since 1.0.0
 */
@Suppress("kutils_null_check")
@OptIn(ExperimentalContracts::class)
operator fun <E> Sequence<E>?.not(): Boolean {
    contract {
        returns(false) implies (this@not != null)
    }
    return isNullOrEmpty()
}

/**
 * Divides the elements of a sequence into two groups based on a given predicate.
 * The result is a pair of lists, where the first list contains elements
 * that satisfy the predicate, and the second list contains elements that do not.
 *
 * @param predicate The condition to partition the elements of the sequence.
 * @return A pair of lists where the first list contains elements satisfying the predicate
 *         and the second list contains the remaining elements.
 * @since 1.0.0
 */
operator fun <E> Sequence<E>.div(predicate: Predicate<E>) = partition(predicate)
/**
 * Splits the elements of the sequence into lists each not exceeding the specified chunk size.
 *
 * The resulting sequence contains lists which group the original sequence's elements.
 * Each list will have a size of at most `chunkSize`. If the number of elements in
 * the sequence is not evenly divisible by `chunkSize`, then the last list in the resulting
 * sequence will contain the remaining elements.
 *
 * @param chunkSize the maximum number of elements in each chunked list.
 * @return a sequence of lists, where each list contains at most `chunkSize` elements.
 * @since 1.0.0
 */
operator fun <E> Sequence<E>.rem(chunkSize: Int): Sequence<List<E>> = chunked(chunkSize)
/**
 * Applies a partitioning operation on the sequence, grouping its elements into continuous chunks
 * that satisfy or do not satisfy the given predicate. The resulting sequence contains lists of elements,
 * where each list corresponds to a chunk determined by the changes in the predicate's condition.
 *
 * @param predicate a function that determines the condition applied to each element in the sequence.
 * @return a sequence of lists, where each list is a chunk of elements based on the predicate.
 * @since 1.0.0
 */
operator fun <E> Sequence<E>.rem(predicate: Predicate<E>): Sequence<List<E>> = chunkedWhile(predicate)

/**
 * Retrieves a subsequence of elements from the original sequence within the specified range.
 *
 * The method drops elements before the start of the range (inclusive) and
 * takes elements up to the end of the range (exclusive) from the sequence.
 *
 * @param T the type of elements in the sequence
 * @param range the range specifying the indices to extract; the start is inclusive, and the end is exclusive
 * @return a sequence containing the elements within the specified range
 * @since 1.0.0
 */
operator fun <T> Sequence<T>.get(range: IntRange) = drop(range.first)
    .take(range.last - range.first + 1)

/**
 * Retrieves an element at the specified index from the sequence.
 *
 * This function skips the specified number of elements in the sequence and then
 * returns the first element encountered. It is useful for random access in a sequence.
 *
 * Note that using this function on a sequence is not efficient for large indices, as it
 * involves iterating through elements sequentially until the specified position is reached.
 *
 * @param int The zero-based index of the element to retrieve from the sequence.
 * @return The element at the specified position in the sequence.
 * @throws NoSuchElementException If the specified index is beyond the bounds of the sequence.
 * @since 1.0.0
 */
operator fun <T> Sequence<T>.get(int: Int) = drop(int).first()

/**
 * Retrieves an element at the specified index from the sequence or returns null
 * if an exception is encountered during the operation.
 *
 * This function combines the behavior of the `get` function and `tryOrNull` to safely
 * access elements by index in a sequence. If the index is out of bounds or another
 * exception occurs, it will return null instead of throwing an exception.
 *
 * Note that accessing elements by index in a sequence is not efficient for large
 * indices, as it involves sequential iteration through the elements.
 *
 * @param T the type of elements in the sequence
 * @param index the zero-based index of the element to retrieve
 * @return the element at the specified index, or null if an exception occurs
 * @since 1.0.0
 */
infix fun <T> Sequence<T>.getOrNull(index: Int) = tryOrNull { get(index) }

/**
 * Retrieves the element at the specified index from a sequence or throws a custom exception if the index
 * is out of bounds.
 *
 * This function attempts to return the element at the given index by traversing the sequence up to the specified
 * position. If the index is invalid (e.g., negative or exceeds the size of the sequence), a custom exception
 * provided by the `lazyException` supplier is thrown.
 *
 * @param index The zero-based index of the element to retrieve from the sequence.
 * @param lazyException A supplier that provides the exception to be thrown if the element at the specified index
 * cannot be retrieved. By default, a `NoSuchElementException` is thrown with a message indicating the invalid index.
 * @return The element of the sequence at the specified index.
 * @throws Throwable The exception provided by `lazyException` if the index is invalid or if an error occurs during
 * the sequence traversal.
 *
 * @since 1.0.0
 */
fun <E> Sequence<E>.getOrThrow(index: Int, lazyException: ThrowableSupplier = { NoSuchElementException("Index $index not present") }): E =
    tryOrThrow(lazyException) { take(index).first() }

/**
 * Sorts the elements of the sequence based on the specified sorting direction.
 *
 * @param direction The sorting direction to apply. Use `SortingDirection.ASCENDING` to sort
 * in ascending order or `SortingDirection.DESCENDING` to sort in descending order.
 * @since 1.0.0
 */
fun <E: Comparable<E>> Sequence<E>.sorted(direction: SortDirection) = when (direction) {
    SortDirection.Ascending -> sorted()
    SortDirection.Descending -> sortedDescending()
}

/**
 * Sorts elements in the sequence based on the specified sorting direction and a selector function.
 * Returns a sequence sorted in ascending or descending order as per the provided direction and selector.
 *
 * @param direction The direction to sort the sequence, either [SortDirection.Ascending] or [SortDirection.Descending].
 * @param selector A lambda function to transform sequence elements into values used for sorting.
 *                 These values must be comparable or nullable comparable.
 * @since 1.0.0
 */
inline fun <E, R : Comparable<R>> Sequence<E>.sortedBy(direction: SortDirection, crossinline selector: Transformer<E, R?>) = when (direction) {
    SortDirection.Ascending -> sortedBy(selector)
    SortDirection.Descending -> sortedByDescending(selector)
}

/**
 * Returns a subsequence of elements that appear before the given element in the sequence.
 * If the given element does not exist in the sequence, an empty sequence is returned.
 *
 * @param element the element in the sequence up to which the subsequence is returned, excluding the element itself.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.before(element: E) = if (contains(element)) get(0..<indexOf(element)) else emptySequence()
/**
 * Returns a new sequence of elements occurring before and including the first appearance of the specified element.
 * If the sequence does not contain the specified element, an empty sequence is returned.
 *
 * @param element The element to search for in the sequence. The resulting sequence includes elements
 *                from the start of the original sequence up to and including the first occurrence of this element.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.beforeIncluding(element: E) = if (contains(element)) get(0..indexOf(element)) else emptySequence()
/**
 * Returns a sequence containing elements of the original sequence that appear before the last occurrence
 * of the specified element. If the specified element is not found, an empty sequence is returned.
 *
 * @param element the element whose last occurrence is used as the boundary for creating the resulting sequence
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.beforeLast(element: E) = if (contains(element)) get(0..<lastIndexOf(element)) else emptySequence()
/**
 * Returns a subsequence of elements from the beginning of the original sequence
 * up to and including the last occurrence of the specified [element].
 * If the [element] does not exist in the sequence, returns an empty sequence.
 *
 * @param element The element to locate within the sequence. The returned sequence
 * includes elements up to and including the last occurrence of this element.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.beforeLastIncluding(element: E) = if (contains(element)) get(0..lastIndexOf(element)) else emptySequence()
/**
 * Returns a sequence containing elements after the specified [element] in the original sequence.
 * If the [element] is not found in the sequence, returns an empty sequence.
 *
 * @param element the element after which the resulting sequence begins
 * @return a sequence of elements after the specified [element]
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.after(element: E) = if (contains(element)) drop(indexOf(element) + 1) else emptySequence()
/**
 * Returns a sequence containing all elements of the original sequence starting from the first occurrence
 * of the specified element, including the element itself. If the element is not found, an empty sequence is returned.
 *
 * @param element the element from which to start the resulting sequence, inclusive.
 * @return a sequence starting from the specified element or an empty sequence if the element is not found.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.afterIncluding(element: E) = if (contains(element)) drop(indexOf(element)) else emptySequence()
/**
 * Creates a new sequence containing all elements after the last occurrence of the specified [element].
 * If the [element] is not present in the sequence, an empty sequence is returned.
 *
 * @param element The element after whose last occurrence the new sequence should start.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.afterLast(element: E) = if (contains(element)) drop(lastIndexOf(element) + 1) else emptySequence()
/**
 * Returns a sequence containing the elements of the original sequence after the last occurrence
 * of the specified [element], including the [element] itself. If the [element] is not present
 * in the sequence, an empty sequence is returned.
 *
 * @param element The element to search for in the sequence. The returned sequence starts
 * from the last occurrence of this element, including it.
 * @since 1.0.0
 */
infix fun <E> Sequence<E>.afterLastIncluding(element: E) = if (contains(element)) drop(lastIndexOf(element)) else emptySequence()

/**
 * Filters elements from the sequence by applying the provided transformer function and
 * checking if the result of the transformation is not null.
 *
 * @param element A transformer function that maps an element of the sequence to another value,
 * which is then checked for nullability.
 * @since 1.0.0
 */
infix fun <E, R> Sequence<E>.filterNotNull(element: Transformer<E, R>) =
    filter { element(it).isNotNull() }

/**
 * Filters elements from the sequence by applying the provided transformer function and
 * checking if the result of the transformation is null.
 *
 * @param element A transformer function that maps an element of the sequence to another value,
 * which is then checked for nullability.
 * @since 1.0.0
 */
infix fun <E, R> Sequence<E>.filterNull(element: Transformer<E, R>) =
    filter { element(it).isNull() }

/**
 * Validates that the sequence is not empty.
 *
 * This function checks if the sequence contains no elements. If the sequence is empty,
 * it throws a `ValidationFailedException` with an optional cause specified by the provided
 * throwable suppliers. If the sequence is not empty, the original sequence is returned.
 *
 * @param causeOf a supplier for providing a specific throwable to be thrown; may be null.
 * @param cause a supplier for providing the underlying cause of the exception; may be null.
 * @return the original sequence if it is not empty.
 * @throws ValidationFailedException if the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException("The sequence is empty.", cause?.invoke()) else causeOf().initCause(ValidationFailedException("The sequence is empty.", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty. If the sequence is empty, it throws a `ValidationFailedException`
 * with an optional cause and message supplied by the provided suppliers.
 *
 * @param causeOf an optional supplier for a specific cause to be used as the root `Throwable`. If `null`, a default
 *                cause is created using `ValidationFailedException`.
 * @param cause an optional supplier for an additional nested cause to be attached to the exception.
 * @param lazyMessage a supplier for the lazy-evaluated message to be used in the exception if validation fails.
 * @return the original sequence if the validation is successful (i.e., the sequence is not empty).
 * @throws ValidationFailedException if the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null, lazyMessage: Supplier<Any>): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(lazyMessage().toString(), cause?.invoke()) else causeOf().initCause(ValidationFailedException(lazyMessage().toString(), cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty.
 *
 * If the sequence is empty, it throws a `ValidationFailedException`. The exception message can
 * include details about the property, variable name, a custom message, and the cause of the failure.
 *
 * @param property The property associated with the validation. Can be null if not applicable.
 * @param variableName The name of the variable being validated. Included in the exception message if provided.
 * @param message An optional custom message to include in the exception if validation fails. Defaults to "is empty".
 * @param causeOf A supplier for the primary cause of the exception, if applicable. Can be null.
 * @param cause A supplier for an additional cause to associate with the exception. Can be null.
 * @return The same sequence that was validated, if it is not empty.
 * @throws ValidationFailedException If the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(property: KProperty<*>?, variableName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variableName, message ?: "is empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variableName, message ?: "is empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty. If the sequence is empty, a `ValidationFailedException` is thrown.
 *
 * @param property the primary property associated with the validation, used for generating contextual information in the exception
 * @param variable an optional secondary property providing additional context, used for detailed exception messages
 * @param message an optional custom error message describing the validation failure
 * @param causeOf a supplier providing a throwable to be used as the main cause of the exception; if null, a default exception is constructed
 * @param cause a supplier providing an additional cause to be attached to the generated `ValidationFailedException`
 * @return the sequence itself if validation passes, allowing for method chaining
 * @throws ValidationFailedException if the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(property: KProperty<*>?, variable: KProperty<*>?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variable, message ?: "is empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variable, message ?: "is empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty. If the sequence is empty, this method throws a
 * ValidationFailedException with the provided details.
 *
 * @param callable The Kotlin function (`KFunction`) to which this validation is related. Can be null.
 * @param parameterName The name of the parameter in the specified callable being validated. Can be null.
 * @param message An optional custom message to include in the exception if validation fails. Defaults to "is empty".
 * @param causeOf A supplier for an exception to be thrown as the root cause if validation fails. Can be null.
 * @param cause A supplier for an additional cause to include in the ValidationFailedException. Can be null.
 * @return The original sequence if the validation passes.
 * @throws ValidationFailedException If the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(callable: KFunction<*>?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameterName, message ?: "is empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameterName, message ?: "is empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty. If the sequence is empty, a `ValidationFailedException` is thrown.
 *
 * @param callable the [KFunction] related to the validation, or null if not applicable.
 * @param parameter the [KParameter] representing the parameter involved in the validation, or null if not applicable.
 * @param message an optional message providing additional context for the validation failure. Defaults to null.
 * @param causeOf an optional supplier for the exception to be thrown if the validation fails. Defaults to null.
 * @param cause an optional supplier for the underlying cause of the validation failure. Defaults to null.
 * @return the validated sequence if it is not empty.
 * @throws ValidationFailedException if the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(callable: KFunction<*>?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameter, message ?: "is empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameter, message ?: "is empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty. If the sequence is empty, a `ValidationFailedException` is thrown.
 *
 * @param callableName the name of the callable (e.g., function or method) related to the validation failure. Can be `null`.
 * @param parameterName the name of the parameter that caused the validation failure. Can be `null`.
 * @param message an optional custom message providing additional details about the validation failure. Defaults to "is empty" if `null`.
 * @param causeOf a supplier for the primary exception that serves as the root cause. Can be `null`.
 * @param cause a supplier for a secondary exception that becomes an underlying cause. Can be `null`.
 * @return the same sequence if it is not empty.
 * @throws ValidationFailedException if the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(callableName: String?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameterName, message ?: "is empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameterName, message ?: "is empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not empty. If the sequence is empty, throws a `ValidationFailedException`.
 *
 * @param callableName The name of the callable where the validation is performed, or null if not specified.
 * @param parameter The `KParameter` instance representing the parameter being validated, or null if not applicable.
 * @param message An optional custom error message to use if validation fails. Defaults to "is empty".
 * @param causeOf A supplier for the specific `Throwable` to throw instead of the default exception, or null if not used.
 * @param cause A supplier for the underlying cause of the validation failure, or null if there is no underlying cause.
 * @return The original sequence if it is not empty.
 * @throws ValidationFailedException if the sequence is empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateNotEmpty(callableName: String?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameter, message ?: "is empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameter, message ?: "is empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not null or empty. If the validation fails, a
 * `ValidationFailedException` is thrown with an optional cause.
 *
 * @param causeOf an optional supplier that provides a throwable to be used as the
 *                primary cause of the validation failure. If null, a default exception
 *                is created.
 * @param cause an optional supplier that provides a throwable which can be linked
 *              as an additional cause to provide more context for the exception.
 * @return the validated sequence if it is not null or empty.
 * @throws ValidationFailedException if the sequence is null or empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException("The sequence is null or empty.", cause?.invoke()) else causeOf().initCause(ValidationFailedException("The sequence is null or empty.", cause?.invoke()))
    return this
}
/**
 * Validates that the given sequence is neither `null` nor empty.
 * If the sequence is `null` or empty, a `ValidationFailedException` is thrown.
 *
 * @param causeOf an optional supplier for a `Throwable` that will serve as the main cause if validation fails.
 * @param cause an optional supplier for a `Throwable` that will be attached as the underlying cause for the validation failure.
 * @param lazyMessage a supplier for the error message to be used in the `ValidationFailedException`, constructed lazily.
 * @return the validated sequence, if it is neither `null` nor empty.
 * @throws ValidationFailedException if the sequence is `null` or empty, with the provided error message and cause(s).
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null, lazyMessage: Supplier<Any>): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(lazyMessage().toString(), cause?.invoke()) else causeOf().initCause(ValidationFailedException(lazyMessage().toString(), cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is neither null nor empty. If the validation fails, a `ValidationFailedException`
 * is thrown with the provided details.
 *
 * @param property The property associated with the validation. Can be null if not applicable.
 * @param variableName An optional name of the variable involved in the validation. Used in the error message if provided.
 * @param message An optional custom message to include in the exception. Defaults to "is null or empty".
 * @param causeOf A supplier for the throwable that should be used as the base exception. If null, a default exception is generated.
 * @param cause A supplier for the throwable that should be used as the direct cause of the validation exception. Can be null.
 * @return The sequence itself if validation passes successfully.
 * @throws ValidationFailedException if the sequence is null or empty, with the provided or default details.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(property: KProperty<*>?, variableName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variableName, message ?: "is null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variableName, message ?: "is null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not null or empty. If the sequence is null or empty, throws a
 * `ValidationFailedException` with an optionally provided message and cause.
 *
 * @param property the primary property associated with the validation failure, or null if not specified
 * @param variable an optional secondary property providing additional context, or null if not specified
 * @param message an optional message explaining the validation failure; defaults to "is null or empty" if not specified
 * @param causeOf an optional supplier for a custom exception to be thrown if the validation fails; defaults to null
 * @param cause an optional supplier for the underlying cause of the exception; defaults to null
 * @return the original sequence if the validation succeeds
 * @throws ValidationFailedException if the sequence is null or empty
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(property: KProperty<*>?, variable: KProperty<*>?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variable, message ?: "is null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variable, message ?: "is null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not `null` or empty. If the validation fails, throws a `ValidationFailedException`.
 *
 * @param callable An optional Kotlin function (`KFunction`) reference associated with the validation context.
 * @param parameterName The name of the parameter being validated. Can be `null` if not applicable.
 * @param message An optional custom message to include in the exception if validation fails.
 * @param causeOf An optional supplier for the exception's primary cause if validation fails.
 * @param cause An optional supplier for the additional cause to be set in the exception if validation fails.
 * @return The validated sequence, if it is not `null` or empty.
 * @throws ValidationFailedException If the sequence is `null` or empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(callable: KFunction<*>?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameterName, message ?: "is null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameterName, message ?: "is null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that a sequence is neither `null` nor empty.
 *
 * Throws a [ValidationFailedException] if the sequence is `null` or empty.
 *
 * @param callable the [KFunction] related to the validation, providing context about the function in which the validation occurs; may be `null`.
 * @param parameter the [KParameter] representing the parameter being validated; may be `null`.
 * @param message an optional message describing the validation failure; default value is `null`.
 * @param causeOf an optional supplier for custom exception to throw as the primary cause; default value is `null`.
 * @param cause an optional supplier for the secondary cause to be attached to the exception; default value is `null`.
 * @return the original sequence if it is not `null` or empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(callable: KFunction<*>?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameter, message ?: "is null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameter, message ?: "is null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is not null or empty. If the sequence is null or empty,
 * throws a `ValidationFailedException` with the specified details.
 *
 * @param callableName The name of the callable (e.g., method, function) related to this validation check.
 * @param parameterName The name of the parameter being validated, which can be null if not applicable.
 * @param message An optional custom message providing more context about the validation failure.
 * @param causeOf A supplier that provides the primary cause of validation failure, or null if not applicable.
 * @param cause A supplier for the underlying throwable cause for the exception, or null if not applicable.
 * @return The sequence itself if the validation passes.
 * @throws ValidationFailedException If the sequence is null or empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(callableName: String?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameterName, message ?: "is null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameterName, message ?: "is null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the given sequence is neither null nor empty.
 * If the sequence is null or empty, a `ValidationFailedException` is thrown.
 *
 * @param callableName The name of the callable (e.g., function or property) associated with the validation,
 *                     or `null` if not specified.
 * @param parameter The `KParameter` instance representing the parameter being validated, or `null` if not applicable.
 * @param message An optional error message providing additional details about the validation failure,
 *                or `null` to use the default message.
 * @param causeOf A supplier for the root cause of the validation failure, which may wrap the generated `ValidationFailedException`,
 *                or `null` if not specified.
 * @param cause A supplier for the cause of the validation failure, or `null` if not specified.
 * @return The original sequence if it is neither null nor empty.
 * @throws ValidationFailedException If the sequence is null or empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNotNullOrEmpty(callableName: String?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNotNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNotNullOrEmpty != null)
    }
    if (isNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameter, message ?: "is null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameter, message ?: "is null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is empty. If the sequence is not empty, a validation exception is thrown.
 *
 * @param causeOf Optional supplier for the throwable that provides additional context for the exception.
 *                If provided, the throwable is used as the primary cause of failure.
 * @param cause Optional supplier for the throwable that serves as the underlying cause of the validation exception.
 * @return The original sequence, if it passes the validation (i.e., it is empty).
 * @throws ValidationFailedException if the sequence is not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException("The sequence is not empty.", cause?.invoke()) else causeOf().initCause(ValidationFailedException("The sequence is not empty.", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is empty and throws a validation exception if it is not.
 *
 * @param causeOf An optional supplier for a throwable to be used as the cause of the exception,
 *                or `null` to ignore this parameter.
 * @param cause An optional supplier for a throwable to be set as the cause of the validation exception,
 *              or `null` if no cause is needed.
 * @param lazyMessage A supplier that generates the error message to be used in the validation exception
 *                    if the sequence is not empty.
 * @return The original sequence if it is empty.
 * @throws ValidationFailedException if the sequence is not empty, constructed with the supplied message
 *                                   and optional cause(s).
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null, lazyMessage: Supplier<Any>): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(lazyMessage().toString(), cause?.invoke()) else causeOf().initCause(ValidationFailedException(lazyMessage().toString(), cause?.invoke()))
    return this
}
/**
 * Validates if the sequence is empty. If the sequence is not empty, throws a `ValidationFailedException`.
 *
 * @param property The property associated with the validation. Can be null if no specific property is involved.
 * @param variableName An optional name of the variable being validated. Included in the error details if provided.
 * @param message An optional custom error message. Defaults to "is not empty" if not specified.
 * @param causeOf A supplier providing a specific `Throwable` instance to be thrown. If null, a default exception is thrown.
 * @param cause A supplier providing the cause of the exception. Can be null if no cause is specified.
 * @return The original sequence, if validation passes.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(property: KProperty<*>?, variableName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variableName, message ?: "is not empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variableName, message ?: "is not empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is empty, throwing a ValidationFailedException if it's not.
 *
 * This method is useful for ensuring that a sequence contains no elements during validation checks.
 * If the sequence is not empty, the specified error details will be used to construct the exception.
 *
 * @receiver The sequence to validate.
 * @param property The main KProperty associated with the validation failure, or null if not specified.
 * @param variable An optional secondary KProperty that provides additional context, or null if not specified.
 * @param message An optional message providing additional details about the validation failure.
 * @param causeOf A supplier for the primary exception cause, or null if not specified.
 * @param cause A supplier for any additional exception cause, or null if not specified.
 * @return The original sequence if it is empty.
 * @throws ValidationFailedException if the sequence is not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(property: KProperty<*>?, variable: KProperty<*>?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variable, message ?: "is not empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variable, message ?: "is not empty", cause?.invoke()))
    return this
}
/**
 * Validates if the sequence is empty. If the sequence is not empty, it throws a [ValidationFailedException].
 *
 * @param callable The Kotlin function (`KFunction`) to which the validation error is related. Can be null.
 * @param parameterName The name of the parameter in the given callable that caused the validation issue. Defaults to null.
 * @param message An optional custom message providing additional details about the validation failure. Defaults to null.
 * @param causeOf A supplier that provides the root cause of the validation failure as a [Throwable]. Defaults to null.
 * @param cause A supplier that provides additional context for the validation failure as a [Throwable]. Defaults to null.
 * @return The original sequence if it is empty.
 * @throws ValidationFailedException if the sequence is not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(callable: KFunction<*>?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameterName, message ?: "is not empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameterName, message ?: "is not empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is empty. If the sequence is not empty, throws a [ValidationFailedException].
 *
 * @param callable The [KFunction] related to the validation, or null if not applicable.
 * @param parameter The [KParameter] representing the parameter involved in the validation, or null if not applicable.
 * @param message An optional message providing additional context about the validation failure. Defaults to "is not empty" if not specified.
 * @param causeOf A supplier for the throwable to be thrown as the root cause, or null if not specified.
 * @param cause A supplier for the underlying exception cause, or null if not specified.
 * @return The original sequence if it is empty.
 * @throws ValidationFailedException If the sequence is not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(callable: KFunction<*>?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameter, message ?: "is not empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameter, message ?: "is not empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is empty and throws a `ValidationFailedException` if it is not.
 *
 * @param callableName The name of the callable (e.g., function or method) related to the validation.
 * @param parameterName The name of the parameter being validated, or null if unspecified.
 * @param message An optional custom message to provide additional context for the validation failure.
 * @param causeOf An optional supplier for the throwable cause of the validation failure, or null if unspecified.
 * @param cause An optional supplier for the underlying cause of the exception, or null if unspecified.
 * @return The same sequence if validation passes.
 * @throws ValidationFailedException If the sequence is not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(callableName: String?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameterName, message ?: "is not empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameterName, message ?: "is not empty", cause?.invoke()))
    return this
}
/**
 * Validates that a sequence is empty. If the sequence is not empty, a `ValidationFailedException` is thrown.
 *
 * This method is useful for enforcing expectations about the emptiness of sequences in validation logic.
 *
 * @param callableName The name of the callable (e.g., function or property) related to the validation. Can be null.
 * @param parameter The parameter associated with the validation, represented as a `KParameter`. Can be null.
 * @param message An optional error message to provide additional context about the validation failure. Defaults to "is not empty" if not specified.
 * @param causeOf A supplier for an optional base cause `Throwable` to be used in creating the exception, or null.
 * @param cause A supplier for an optional `Throwable` detailing additional context for the exception, or null.
 * @return The original sequence if it is empty.
 * @throws ValidationFailedException If the sequence is not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>, E> T.validateEmpty(callableName: String?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    if (isNotEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameter, message ?: "is not empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameter, message ?: "is not empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is either null or empty. If the sequence does not meet the condition,
 * it throws a [ValidationFailedException].
 *
 * @param causeOf An optional supplier for a [Throwable] that serves as the primary cause of the exception,
 *                or `null`. If provided, this will be used as the root cause.
 * @param cause An optional supplier for a secondary [Throwable] that will be wrapped as the cause of the
 *              [ValidationFailedException], or `null`.
 * @return The original sequence if it passes the validation (i.e., it is null or empty).
 * @throws ValidationFailedException if the sequence is not null or empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException("The sequence is not null or empty.", cause?.invoke()) else causeOf().initCause(ValidationFailedException("The sequence is not null or empty.", cause?.invoke()))
    return this
}
/**
 * Validates that a sequence is either null or empty.
 * If the sequence is neither null nor empty, a `ValidationFailedException` is thrown.
 *
 * @param causeOf A supplier for a throwable that will be raised if the validation fails.
 *                This throwable will be set as the cause of the thrown exception if provided.
 * @param cause An additional supplier of a throwable that can be used as a cause for context.
 *              If provided, this will be linked as a cause to the supplied `causeOf` throwable
 *              or directly to the `ValidationFailedException`.
 * @param lazyMessage A supplier for the error message used in the exception if validation fails.
 *                    This allows for lazy evaluation of the error message.
 * @return The same sequence on which the validation was performed.
 *         If the sequence passes the validation (is null or empty), it is returned as-is.
 * @throws ValidationFailedException If the sequence is neither null nor empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null, lazyMessage: Supplier<Any>): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(lazyMessage().toString(), cause?.invoke()) else causeOf().initCause(ValidationFailedException(lazyMessage().toString(), cause?.invoke()))
    return this
}
/**
 * Validates whether the sequence is either null or empty. If the sequence is not null and not empty,
 * a `ValidationFailedException` is thrown.
 *
 * @param property The property associated with the validation. Can be null if not applicable.
 * @param variableName The name of the variable being validated. Can be null if not provided.
 * @param message An optional custom message for the validation error. Defaults to "is not null or empty".
 * @param causeOf An optional supplier for the cause of the exception to be thrown. If not null, it will be invoked
 *                to provide a `Throwable`.
 * @param cause An optional supplier for an additional throwable cause to be associated with the exception. If not null,
 *              it will be invoked to provide the cause.
 * @return The same sequence instance if the validation does not fail.
 * @throws ValidationFailedException If the sequence is not null and not empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(property: KProperty<*>?, variableName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variableName, message ?: "is not null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variableName, message ?: "is not null or empty", cause?.invoke()))
    return this
}
/**
 * Validates whether the sequence is null or empty and throws a [ValidationFailedException] if it is not.
 *
 * @param property the main [KProperty] associated with the validation, providing context for the error, or null if not applicable
 * @param variable an additional [KProperty] offering further context, or null if not applicable
 * @param message an optional error message to include in the exception if validation fails, or null for a default message
 * @param causeOf a [ThrowableSupplier] that supplies the root cause of the validation failure, or null if not specified
 * @param cause a [ThrowableSupplier] providing a supplementary cause for the [ValidationFailedException], or null if not specified
 * @return the original sequence if it passes validation
 * @throws ValidationFailedException if the sequence is not null or empty
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(property: KProperty<*>?, variable: KProperty<*>?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(property, variable, message ?: "is not null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(property, variable, message ?: "is not null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is either null or empty. If the sequence is neither null nor empty,
 * a `ValidationFailedException` is thrown with the provided details.
 *
 * @param callable The Kotlin function (`KFunction`) to which the validation is related. Can be null.
 * @param parameterName The name of the parameter being validated. Can be null.
 * @param message An optional custom message for the exception. Default is "is not null or empty".
 * @param causeOf A supplier for the `Throwable` that represents the root cause of the validation failure. Can be null.
 * @param cause A supplier for the `Throwable` that provides additional context to the exception. Can be null.
 * @return The same sequence after validation.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(callable: KFunction<*>?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameterName, message ?: "is not null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameterName, message ?: "is not null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the given sequence is either `null` or empty. If the sequence is not `null` or empty,
 * a `ValidationFailedException` is thrown.
 *
 * @param callable the [KFunction] associated with the validation failure, or `null` if not applicable.
 * @param parameter the [KParameter] representing the parameter being validated, or `null` if not applicable.
 * @param message an optional message providing additional details about the validation failure, defaulting to a standard message.
 * @param causeOf a supplier for the root cause of the validation failure, or `null` if not applicable.
 * @param cause an optional supplier for additional context on the cause of the failure, or `null` if not specified.
 * @return the original sequence if it passes validation without exceptions.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(callable: KFunction<*>?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callable, parameter, message ?: "is not null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callable, parameter, message ?: "is not null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that the sequence is either null or empty. If the sequence is not null and not empty,
 * a `ValidationFailedException` is thrown.
 *
 * @param callableName the name of the callable (e.g., function or method) where the validation is performed
 * @param parameterName the name of the parameter being validated; optional
 * @param message an optional custom message providing additional details about the validation failure
 * @param causeOf a supplier that provides a custom throwable to be thrown as the cause of the failure; optional
 * @param cause a supplier that provides an additional cause for the `ValidationFailedException`; optional
 * @return the original sequence if validation passes
 * @throws ValidationFailedException if the sequence is not null and not empty
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(callableName: String?, parameterName: String? = null, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameterName, message ?: "is not null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameterName, message ?: "is not null or empty", cause?.invoke()))
    return this
}
/**
 * Validates that a sequence is null or empty. Throws a [ValidationFailedException]
 * if the sequence is neither null nor empty.
 *
 * @param callableName The name of the callable where the validation is performed. This may be null if not applicable.
 * @param parameter The [KParameter] associated with the validation. This may be null if not applicable.
 * @param message An optional custom error message to be included in the exception if validation fails. Defaults to "is not null or empty".
 * @param causeOf A supplier for an optional root cause of the validation failure. If provided, it initializes the throwable chain with the supplied cause.
 * @param cause A supplier for an optional additional cause of the failure. If provided, this is set as the cause of the [ValidationFailedException].
 * @return The original sequence if it passes the validation (i.e., if it is null or empty).
 * @throws ValidationFailedException If the sequence is neither null nor empty.
 * @since 4.2.0
 */
@IgnorableReturnValue
fun <T : Sequence<E>?, E> T.validateNullOrEmpty(callableName: String?, parameter: KParameter?, message: String? = null, causeOf: ThrowableSupplier? = null, cause: ThrowableSupplier? = null): T {
    contract {
        (this@validateNullOrEmpty != null) implies returnsNotNull()
        returnsNotNull() implies (this@validateNullOrEmpty != null)
    }
    if (isNotNullOrEmpty()) throw if (causeOf.isNull()) ValidationFailedException(callableName, parameter, message ?: "is not null or empty", cause?.invoke()) else causeOf().initCause(ValidationFailedException(callableName, parameter, message ?: "is not null or empty", cause?.invoke()))
    return this
}